# Generated by Django 5.0.6 on 2024-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('propellant', models.CharField(max_length=50)),
                ('calibre', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('magazine_capacity', models.IntegerField()),
                ('first_manufactured', models.DateField(null=True)),
            ],
        ),
    ]
